---
apiVersion: v1
kind: Service
metadata:
  annotations:
    k8s.score.dev/workload-name: example
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: example-da65c465ce
    app.kubernetes.io/managed-by: score-k8s
    app.kubernetes.io/name: example
  name: example
spec:
  ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: example-da65c465ce
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    k8s.score.dev/workload-name: example
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: example-da65c465ce
    app.kubernetes.io/managed-by: score-k8s
    app.kubernetes.io/name: example
  name: example
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: example-da65c465ce
  strategy: {}
  template:
    metadata:
      annotations:
        k8s.score.dev/workload-name: example
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: example-da65c465ce
        app.kubernetes.io/managed-by: score-k8s
        app.kubernetes.io/name: example
    spec:
      containers:
        - image: stefanprodan/podinfo
          name: main

          resources: {}
        - image: stefanprodan/podinfo
          name: test
          resources: {}
status: {}
