argo-cd:
  # Values to enable the score-k8s CMP sidecar in the Argo CD Helm chart
  repoServer:
    # -- Additional volumes to the repo server pod
    # We need to add a dedicated tmp volume for our CMP sidecar
    volumes:
      - name: cmp-tmp
        emptyDir: {}
      - name: score-data
        persistentVolumeClaim:
          claimName: argo-score

    # -- Additional containers to be added to the repo server pod
    # Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/
    extraContainers:
      - name: score-k8s-plugin
        # This is the lightweight server that Argo CD uses to communicate with the plugin.
        command:
          - /var/run/argocd/argocd-cmp-server
        # Replace this with the image you built and pushed in the previous step.
        image: your-registry/score-k8s-plugin:latest
        imagePullPolicy: Never
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
          # Mount the same standard volumes as the main repo-server container.
          - mountPath: /var/run/argocd
            name: var-files

          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          # Mount the dedicated tmp volume.
          # This enhances security by separating the filesystem from the main repo-server.
          - mountPath: /tmp
            name: cmp-tmp

          - mountPath: /data
            name: score-data
