---
apiVersion: v1
kind: Service
metadata:
    annotations:
        k8s.score.dev/workload-name: service-a
    creationTimestamp: null
    labels:
        app.kubernetes.io/instance: service-a-79458a0f82
        app.kubernetes.io/managed-by: score-k8s
        app.kubernetes.io/name: service-a
    name: service-a
spec:
    ports:
        - name: www
          port: 8000
          protocol: TCP
          targetPort: 80
    selector:
        app.kubernetes.io/instance: service-a-79458a0f82
status:
    loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        k8s.score.dev/workload-name: service-a
    creationTimestamp: null
    labels:
        app.kubernetes.io/instance: service-a-79458a0f82
        app.kubernetes.io/managed-by: score-k8s
        app.kubernetes.io/name: service-a
    name: service-a
spec:
    selector:
        matchLabels:
            app.kubernetes.io/instance: service-a-79458a0f82
    strategy: {}
    template:
        metadata:
            annotations:
                k8s.score.dev/workload-name: service-a
            creationTimestamp: null
            labels:
                app.kubernetes.io/instance: service-a-79458a0f82
                app.kubernetes.io/managed-by: score-k8s
                app.kubernetes.io/name: service-a
        spec:
            containers:
                - image: busybox
                  name: container-id
                  resources: {}
status: {}
